### ISSUE TITLE
Does this actually work in a Github README?

### ISSUE THREAD

**Issue by zbeekman** [tatey/img2base64#1]
Your base64 encoded image isn't showing up on your readme.

**Comment by tatey** [comment]
No, it appears that GitHub is stripping the base64 encoded string when rendering HTML. I was using this for my Jekyll based blog where I can enable or disable rendering base64 encoded images. You might have better luck there.

I've also updated the gem to output a HTML formatted base64 encoded image too. See the README.

Thanks for your interest in the project.
